/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class AppTest {
  @Test
  fun testPasses() {
    // Simple test that always passes
    assertTrue(true, "This test should always pass")
  }
}
